### ISSUE TITLE
1.2 release checklist

### ISSUE THREAD

**Issue by DeltaDizzy** [Mrcarrot1/DoubleDouble-Redoubled#4]
DDR v1.2 RELEASE CHECKLIST
=========================================

- [ ] Massive quality improvement
- [ ] Proto
- [ ] Karm System (Binary)
- [ ] Kharlinska
- [ ] Vorutrix
- [ ] Ancianx
- [ ] Planet or Star named after Devs
- [ ] SFVE Support
- [ ] Binary Neutron Star-Quark Star system
- [ ] GUMDROP PLANETS
